<a class="gallery_bodyload" id="clickbanner" href="#inline_gallery_bodyload" ></a>
<div style="display:none;z-index:10000" id="inline_gallery_bodyload">
  <div class="modal-body">
        <div id="popup_image"><img src="/skin/frontend/base/default/images/error.png"></div>
		<div id="popup_message"></div>
		<a href="javascript:jQuery.fancybox.close();" class="closis">Tamam</a>
      </div>
</div>
<style>
.closis {
    background: none repeat scroll 0 0 #CE2958;
    border-radius: 3px;
    color: white;
    display: inline-block;
    font-size: 16px;
    font-weight: 700;
    margin: 0 10px 10px 0;
    padding: 10px;
}
.closis:hover  {
    color: white;
}
#popup_message{
    font-size: 16px;
    font-weight: 700;
}	
</style>
